# Generated by Django 5.1.1 on 2024-11-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_profile_image'),
        ('transaction', '0002_transaction_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
