# Generated by Django 5.1.1 on 2024-11-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_requests', '0001_initial'),
        ('students', '0005_student_password_student_username'),
        ('tutors', '0002_tutor_password_tutor_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.tutor'),
        ),
    ]
