# Generated by Django 5.1.1 on 2024-11-28 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutors.tutor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
