# Generated by Django 5.1.3 on 2024-12-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_assignment_created_at_assignment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
