# Generated by Django 5.1.1 on 2024-11-06 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_subject_alter_course_course_code'),
        ('session', '0001_initial'),
        ('students', '0002_student_course_student_fullname_student_section'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.tutor'),
        ),
    ]
