# Generated by Django 5.1.1 on 2024-11-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Default Course', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='fullname',
            field=models.CharField(default='Default Full Name', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='Default Section', max_length=10),
        ),
    ]
