# Generated by Django 5.1.3 on 2024-12-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
